package lsp

import (
	"log/slog"

	"github.com/doors-dev/gox/internal/common"
	jsonrpc2 "github.com/doors-dev/gox/internal/jsonrpc"
	"github.com/doors-dev/gox/internal/workspace"
)

func initClientNotifs(on func(on onNotif, m ...method)) {

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if kind == workspace.KindUnknown {
			n.forward()
			return
		}
		version, err := jsonDoc.getVersion(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		text, err := jsonDoc.getText(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if doc.Err() != nil {
			n.err(common.FromErr(jsonrpc2.ErrUnknown, doc.Err()))
			return
		}
		switch kind {
		case workspace.KindSource:
			doc.SourceOpen(int32(version))
			upd, _ := doc.SourceUpdate(text)
			if upd && doc.TargetIsOpened() {
				n.session().callClient(
					applyEdit,
					jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), "regenerated by .gox file"),
				)
				return
			}
			if doc.TargetIsOpened() {
				return
			}
			jsonDoc.setAsTarget(j, doc)
			n.notify(j)
		case workspace.KindTarget:
			doc.TargetOpen(int32(version))
			if !doc.SourceIsOpened() {
				jsonDoc.setVersion(j, 0)
				n.notify(j)
			}
			doc.TargetDraftUpdate(text)
			if !doc.SubmitTargetDraft() {
				n.session().callClient(
					applyEdit,
					jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), "regenerated by .gox file"),
				)
			}
		}
	}, didOpen)

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if kind == workspace.KindUnknown {
			n.forward()
			return
		}
		if doc.Err() != nil {
			n.err(common.FromErr(jsonrpc2.ErrUnknown, doc.Err()))
			return
		}
		slog.Info("did change", "kind", kind)
		switch kind {
		case workspace.KindSource:
			changes, err := jsonChanges.getChanges(j)
			if err != nil {
				n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
				return
			}
			updated := false
			for _, change := range changes {
				if change.Range.IsValid() {
					upd, _ := doc.SourcePatch(n.enc(), change.Range, change.Text)
					updated = updated || upd
				} else {
					upd, _ := doc.SourceUpdate(change.Text)
					updated = updated || upd
				}
			}
			if !updated {
				return
			}
			doc.Assemble()
			jsonDoc.setAsTarget(j, doc)
			jsonChanges.setUpdate(j, doc.TargetContent())
			n.notify(j)
			if doc.TargetIsOpened() {
				slog.Info("push changes tp target")
				n.session().callClient(
					applyEdit,
					jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), ""),
				)
			}
		case workspace.KindTarget:
			changes, err := jsonChanges.getChanges(j)
			if err != nil {
				n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
				return
			}
			for _, change := range changes {
				if change.Range.IsValid() {
					doc.TargetDraftPatch(n.enc(), change.Range, change.Text)
				} else {
					doc.TargetDraftUpdate(change.Text)
				}
			}
			if doc.SubmitTargetDraft() {
				return
			}
			n.session().callClient(
				applyEdit,
				jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), "[code restored] please edit the original .gox file"),
			)
		}
	}, didChange)

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if kind == workspace.KindUnknown {
			n.forward()
			return
		}
		if kind == workspace.KindTarget {
			return
		}
		if doc.Err() != nil {
			n.err(common.FromErr(jsonrpc2.ErrUnknown, doc.Err()))
			return
		}
		err = doc.Save()
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInternal, err))
			return
		}
		jsonDoc.setAsTarget(j, doc)
		n.notify(j)
	}, didSave)

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if kind == workspace.KindUnknown {
			n.forward()
			return
		}
		if doc.Err() != nil {
			n.err(common.FromErr(jsonrpc2.ErrUnknown, doc.Err()))
			return
		}
		switch kind {
		case workspace.KindSource:
			slog.Info("source file closed: " + doc.SourceFile().Path())
			doc.SourceClose()
			if doc.TargetIsOpened() {
				return
			}
			jsonDoc.setAsTarget(j, doc)
			n.notify(j)
		case workspace.KindTarget:
			doc.TargetClose()
			if doc.SourceIsOpened() {
				return
			}
			n.forward()
		}
	}, didClose)

	on(func(n notifier, j Json) {
		added, removed, err := jsonInit.getWorkspaceChanges(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		for _, uri := range added {
			n.session().addWorkspace(uri)
		}
		for _, uri := range removed {
			n.session().removeWorkspace(uri)
		}
		n.forward()
	}, didChangeWorkspaceFolders)

}
