package lsp

import (
	"github.com/doors-dev/gox/internal/common"
	jsonrpc2 "github.com/doors-dev/gox/internal/jsonrpc"
	"github.com/doors-dev/gox/internal/workspace"
)

func initClientNotifs(sess *session, on func(on onNotif, m ...method)) {
	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(sess.man(), j, false)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if kind == workspace.KindUnknown {
			n.forward()
			return
		}
		version, err := jsonDoc.getVersion(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		text, err := jsonDoc.getText(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if doc.Err() != nil {
			n.err(common.FromErr(jsonrpc2.ErrUnknown, doc.Err()))
			return
		}
		switch kind {
		case workspace.KindSource:
			doc.SourceOpen(int32(version))
			upd, _ := doc.SourceUpdate(text)
			if upd && doc.TargetIsOpened() {
				sess.callClient(
					applyEdit,
					jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), "regenerated by .gox file"),
				)
				return
			}
			if doc.TargetIsOpened() {
				return
			}
			jsonDoc.setAsTarget(j, doc)
			n.notify(j)
		case workspace.KindTarget:
			doc.TargetOpen(int32(version))
			if !doc.SourceIsOpened() {
				jsonDoc.setVersion(j, 0)
				n.notify(j)
			}
			doc.TargetDraftUpdate(text)
			if !doc.SubmitTargetDraft() {
				sess.callClient(
					applyEdit,
					jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), "regenerated by .gox file"),
				)
			}
		}
	}, didOpen)

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(sess.man(), j, true)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if kind == workspace.KindUnknown {
			n.forward()
			return
		}
		if doc == nil && kind == workspace.KindTarget {
			sess.showWarn("editing generated file that does not belong current workspace")
			n.forward()
			return
		}
		if doc.Err() != nil {
			n.err(common.FromErr(jsonrpc2.ErrUnknown, doc.Err()))
			return
		}
		switch kind {
		case workspace.KindSource:
			changes, err := jsonChanges.getChanges(j)
			if err != nil {
				n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
				return
			}
			updated := false
			for _, change := range changes {
				var upd bool
				if change.Range.IsValid() {
					upd, err = doc.SourcePatch(sess.enc(), change.Range, change.Text)
					updated = updated || upd
				} else {
					upd, err = doc.SourceUpdate(change.Text)
					updated = updated || upd
				}
				if err != nil {
					break
				}
			}
			if err != nil {
				n.err(common.FromErr(jsonrpc2.ErrInternal, err))
				return
			}
			if updated {
				doc.Assemble()
			}
			jsonDoc.setAsTarget(j, doc)
			jsonChanges.setUpdate(j, doc.TargetContent())
			n.notify(j)
			if updated && doc.TargetIsOpened() {
				sess.callClient(
					applyEdit,
					jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), ""),
				)
			}
			if updated {
				pos, do := doc.GoxImportPos(sess.enc())
				if !do {
					return
				}
				edit := jsonGenerator.newInsertEdit(
					doc.SourceFile().URI(),
					pos,
					"\n\nimport \"github.com/doors-dev/gox\"",
					"GoX imported",
				)
				sess.callClient(
					applyEdit,
					edit,
				)
			}
		case workspace.KindTarget:
			changes, err := jsonChanges.getChanges(j)
			if err != nil {
				n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
				return
			}
			for _, change := range changes {
				if change.Range.IsValid() {
					err = doc.TargetDraftPatch(sess.enc(), change.Range, change.Text)
				} else {
					err = doc.TargetDraftUpdate(change.Text)
				}
				if err != nil {
					break
				}
			}
			if err != nil {
				n.err(common.FromErr(jsonrpc2.ErrInternal, err))
				return
			}
			if doc.SubmitTargetDraft() {
				return
			}
			sess.callClient(
				applyEdit,
				jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), "[code restored] please edit the original .gox file"),
			)
		}
	}, didChange)

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(sess.man(), j, true)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if doc == nil && kind == workspace.KindTarget {
			sess.showWarn("saving generated file that does not belong current workspace")
			n.forward()
			return
		}
		if kind == workspace.KindUnknown {
			n.forward()
			return
		}
		if kind == workspace.KindTarget {
			return
		}
		if doc.Err() != nil {
			n.err(common.FromErr(jsonrpc2.ErrUnknown, doc.Err()))
			return
		}
		err = doc.Save()
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInternal, err))
			return
		}
		jsonDoc.setAsTarget(j, doc)
		n.notify(j)
	}, didSave)

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(sess.man(), j, false)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		if kind == workspace.KindUnknown {
			n.forward()
			return
		}
		if doc.Err() != nil {
			n.err(common.FromErr(jsonrpc2.ErrUnknown, doc.Err()))
			return
		}
		switch kind {
		case workspace.KindSource:
			doc.SourceClose()
			if doc.TargetIsOpened() {
				return
			}
			jsonDoc.setAsTarget(j, doc)
			n.notify(j)
		case workspace.KindTarget:
			doc.TargetClose()
			if doc.SourceIsOpened() {
				return
			}
			n.forward()
		}
	}, didClose)

	on(func(n notifier, j Json) {
		added, removed, err := jsonInit.getWorkspaceChanges(j)
		if err != nil {
			n.err(common.FromErr(jsonrpc2.ErrInvalidParams, err))
			return
		}
		for _, uri := range added {
			sess.addWorkspace(uri)
		}
		for _, uri := range removed {
			sess.removeWorkspace(uri)
		}
		n.forward()
	}, didChangeWorkspaceFolders)

}
