package lsp

import (
	"log/slog"

	"github.com/doors-dev/gox/internal/walker"
)

func initClientNotifs(on func(on onNotif, m ...method)) {

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(j)
		if err != nil {
			n.err(err)
			return
		}
		if kind == walker.KindUnknown {
			n.forward()
			return
		}
		version, err := jsonDoc.getVersion(j)
		if err != nil {
			n.err(err)
			return
		}
		text, err := jsonDoc.getText(j)
		if err != nil {
			n.err(err)
			return
		}
		err = doc.Lock()
		if err != nil {
			n.err(doc.Err())
			return
		}
		defer doc.Unlock()
		switch kind {
		case walker.KindSource:
			doc.SourceOpen(int32(version))
			upd, _ := doc.SourceUpdate(text)
			if upd && doc.TargetIsOpened() {
				n.session().callClient(
					applyEdit,
					jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), "regenerated by .gox file"),
				)
				return
			}
			if doc.TargetIsOpened() {
				return
			}
			jsonDoc.setAsTarget(j, doc)
			n.notify(j)
		case walker.KindTarget:
			doc.TargetOpen(int32(version))
			if !doc.SourceIsOpened() {
				jsonDoc.setVersion(j, 0)
				n.notify(j)
			}
			doc.TargetDraftUpdate(text)
			if !doc.SubmitTargetDraft() {
				n.session().callClient(
					applyEdit,
					jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), "regenerated by .gox file"),
				)
			}
		}
	}, didOpen)

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(j)
		if err != nil {
			n.err(err)
			return
		}
		if kind == walker.KindUnknown {
			n.forward()
			return
		}
		err = doc.Lock()
		if err != nil {
			n.err(doc.Err())
			return
		}
		defer doc.Unlock()
		switch kind {
		case walker.KindSource:
			changes, err := jsonChanges.getChanges(j)
			if err != nil {
				n.err(err)
				return
			}
			updated := false
			for _, change := range changes {
				if change.Range.IsValid() {
					upd, _ := doc.SourcePatch(n.enc(), change.Range, change.Text)
					updated = updated || upd
				} else {
					upd, _ := doc.SourceUpdate(change.Text)
					updated = updated || upd
				}
			}
			if !updated {
				return
			}
			doc.Assemble()
			jsonDoc.setAsTarget(j, doc)
			jsonChanges.setUpdate(j, doc.TargetContent())
			n.notify(j)
			if doc.TargetIsOpened() {
				n.session().callClient(
					applyEdit,
					jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), ""),
				)
			}
		case walker.KindTarget:
			changes, err := jsonChanges.getChanges(j)
			if err != nil {
				n.err(err)
				return
			}
			for _, change := range changes {
				if change.Range.IsValid() {
					doc.TargetDraftPatch(n.enc(), change.Range, change.Text)
				} else {
					doc.TargetDraftUpdate(change.Text)
				}
			}
			if doc.SubmitTargetDraft() {
				return
			}
			n.session().callClient(
				applyEdit,
				jsonGenerator.newUpdateEdit(doc.TargetFile().URI(), doc.TargetContent(), ""),
			)
		}
	}, didChange)

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(j)
		if err != nil {
			n.err(err)
			return
		}
		if kind == walker.KindUnknown {
			n.forward()
			return
		}
		if kind == walker.KindTarget {
			return
		}
		err = doc.Lock()
		if err != nil {
			n.err(doc.Err())
			return
		}
		defer doc.Unlock()
		err = doc.Save()
		if err != nil {
			n.err(err)
			return
		}
		jsonDoc.setAsTarget(j, doc)
		n.notify(j)
	}, didSave)

	on(func(n notifier, j Json) {
		doc, kind, err := jsonDoc.get(j)
		if err != nil {
			n.err(err)
			return
		}
		if kind == walker.KindUnknown {
			n.forward()
			return
		}
		err = doc.Lock()
		if err != nil {
			n.err(doc.Err())
			return
		}
		defer doc.Unlock()
		switch kind {
		case walker.KindSource:
			slog.Info("source file closed: " + doc.SourceFile().Path())
			doc.SourceClose()
			if doc.TargetIsOpened() {
				return
			}
			jsonDoc.setAsTarget(j, doc)
			n.notify(j)
		case walker.KindTarget:
			doc.TargetClose()
			if doc.SourceIsOpened() {
				return
			}
			n.forward()
		}
	}, didClose)

}
